/*
 * Generate static AI hints for the question bank.
 *
 * PowerShell:
 *   $env:OPENAI_API_KEY = "your-key"
 *   node generate-hints.js
 *
 * Useful options:
 *   node generate-hints.js --limit=10
 *   node generate-hints.js --concurrency=4
 *   node generate-hints.js --force
 *
 * The output is saved after every question, so an interrupted run can resume.
 */
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const questionsPath = path.join(__dirname, "questions.js");
const outputPath = path.join(__dirname, "hints.js");

function loadLocalEnvironment() {
  const environmentPath = path.join(__dirname, ".env");
  if (!fs.existsSync(environmentPath)) return;
  for (const line of fs.readFileSync(environmentPath, "utf8").split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/);
    if (!match || match[1].startsWith("#") || process.env[match[1]]) continue;
    let value = match[2];
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    process.env[match[1]] = value;
  }
}

loadLocalEnvironment();
const apiKey = process.env.OPENAI_API_KEY;
const model = process.env.OPENAI_MODEL || "gpt-5.6-luna";
const force = process.argv.includes("--force");
const limitArgument = process.argv.find((argument) => argument.startsWith("--limit="));
const limit = limitArgument ? Number(limitArgument.split("=")[1]) : Infinity;
const concurrencyArgument = process.argv.find((argument) => argument.startsWith("--concurrency="));
const concurrency = concurrencyArgument ? Number(concurrencyArgument.split("=")[1]) : 4;
const promptVersion = 2;

if (!apiKey) {
  console.error("缺少 OPENAI_API_KEY。請先在終端機設定環境變數，再重新執行。");
  process.exit(1);
}
if (!Number.isFinite(limit) && limit !== Infinity || limit < 1) {
  console.error("--limit 必須是大於 0 的數字。");
  process.exit(1);
}
if (!Number.isInteger(concurrency) || concurrency < 1 || concurrency > 8) {
  console.error("--concurrency 必須是 1 到 8 的整數。");
  process.exit(1);
}

function loadWindowValue(filePath, propertyName) {
  const sandbox = { window: {} };
  vm.runInNewContext(fs.readFileSync(filePath, "utf8"), sandbox, { filename: filePath });
  return sandbox.window[propertyName];
}

function loadExistingHints() {
  if (!fs.existsSync(outputPath)) return {};
  try {
    return loadWindowValue(outputPath, "QUESTION_HINTS") || {};
  } catch (error) {
    throw new Error(`無法讀取既有 hints.js：${error.message}`);
  }
}

function saveHints(hints) {
  const banner = "// Generated by generate-hints.js. It is safe to deploy this file; it contains no API key.\n";
  fs.writeFileSync(outputPath, `${banner}window.QUESTION_HINTS = ${JSON.stringify(hints, null, 2)};\n`, "utf8");
}

function sleep(milliseconds) {
  return new Promise((resolve) => setTimeout(resolve, milliseconds));
}

function extractOutputText(data) {
  if (typeof data.output_text === "string") return data.output_text;
  for (const item of data.output || []) {
    for (const content of item.content || []) {
      if (content.type === "output_text" && typeof content.text === "string") return content.text;
    }
  }
  throw new Error("API 回應沒有文字內容。");
}

async function createHint(question) {
  const input = {
    chapter: question.chapter,
    question: question.text,
    options: question.options,
    correctAnswer: {
      key: question.answer,
      text: question.options[question.answer]
    }
  };

  const response = await fetch("https://api.openai.com/v1/responses", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      model,
      instructions: [
        "你是台灣遙控無人機學科測驗的教學助理。全程使用自然、精簡的繁體中文。",
        "請根據提供的題目、選項與正確答案，產生兩個循序漸進的提示和一段作答後解析。",
        "hint1 只提醒應思考的概念，不得透露答案、選項代號或直接引用正確選項。",
        "hint2 可以協助排除錯誤方向，但仍不得透露答案、選項代號或直接引用正確選項。",
        "explanation 可在作答後清楚說明正確答案的理由，但不得提及 A、B、C、D 選項代號，因為前端會打亂選項順序。不要聲稱題目沒有提供的法條號碼、數值或最新規定。",
        "每個提示最多 55 個中文字；解析最多 100 個中文字。不要使用 Markdown。"
      ].join("\n"),
      input: JSON.stringify(input),
      text: {
        format: {
          type: "json_schema",
          name: "drone_question_hint",
          strict: true,
          schema: {
            type: "object",
            properties: {
              hint1: { type: "string" },
              hint2: { type: "string" },
              explanation: { type: "string" }
            },
            required: ["hint1", "hint2", "explanation"],
            additionalProperties: false
          }
        }
      },
      max_output_tokens: 500,
      store: false
    })
  });

  if (!response.ok) {
    const detail = await response.text();
    const error = new Error(`OpenAI API ${response.status}: ${detail.slice(0, 500)}`);
    error.status = response.status;
    throw error;
  }

  const result = JSON.parse(extractOutputText(await response.json()));
  for (const key of ["hint1", "hint2", "explanation"]) {
    if (typeof result[key] !== "string" || !result[key].trim()) {
      throw new Error(`API 回應缺少 ${key}。`);
    }
    result[key] = result[key].trim();
  }
  return result;
}

async function createHintWithRetry(question) {
  const attempts = 5;
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      return await createHint(question);
    } catch (error) {
      const retryable = error.status === 429 || error.status >= 500 || !error.status;
      if (!retryable || attempt === attempts) throw error;
      const delay = 1000 * (2 ** (attempt - 1));
      console.warn(`  暫時失敗，${delay / 1000} 秒後重試（${attempt}/${attempts}）`);
      await sleep(delay);
    }
  }
}

async function main() {
  const questions = loadWindowValue(questionsPath, "QUESTION_BANK");
  if (!Array.isArray(questions) || !questions.length) throw new Error("questions.js 沒有有效題目。");

  const hints = loadExistingHints();
  const pending = questions.filter((question) => {
    const existing = hints[question.id];
    return force || !existing || existing.promptVersion !== promptVersion;
  }).slice(0, limit);

  if (!pending.length) {
    console.log(`所有 ${questions.length} 題都已有最新版提示。`);
    return;
  }

  console.log(`模型：${model}；待產生：${pending.length} 題；並行數：${concurrency}；完成後寫入 ${outputPath}`);
  let nextIndex = 0;
  let completed = 0;
  async function worker() {
    while (nextIndex < pending.length) {
      const question = pending[nextIndex];
      nextIndex += 1;
      const generated = await createHintWithRetry(question);
      hints[question.id] = {
        ...generated,
        promptVersion,
        model
      };
      saveHints(hints);
      completed += 1;
      console.log(`[${completed}/${pending.length}] ${question.id} 完成`);
    }
  }
  await Promise.all(Array.from({ length: Math.min(concurrency, pending.length) }, () => worker()));
  console.log(`已產生 ${pending.length} 題；hints.js 目前共有 ${Object.keys(hints).length} 題。`);
}

main().catch((error) => {
  console.error(`產生失敗：${error.message}`);
  process.exitCode = 1;
});
